__target__: CoupledVMArch
edge_aggr: max
frame_knn: 32
patch_size: 1000
seed_k: 6
seed_k_alpha: 1
num_train_points: 128
feat_embedding_dim: 256
decoder_hidden_dim: 64
dsm_sigma: 0.01
num_modules: 4
tot_its: 3
consistency_weight: 10.0
# vm_ckpt: set in configs/task/train_cvm_max.yaml
