__target__: StraightPCF
frame_knn: 32
num_train_points: 128
feat_embedding_dim: 128
cvm_feat_embedding_dim: 256
freeze_velocity_nets: true
decoder_hidden_dim: 64
dsm_sigma: 0.01
distance_estimation: true
num_modules: 2
tot_its: 2
patch_size: 1000
seed_k: 6
seed_k_alpha: 1
niters: 1
