mode: predict
debug: false

load_ckpt: experiments/vm_max_multires/checkpoint_99.pkl

components:
  data: predict_cloud
  transform: predict
  system: vm
  model: vm_max

writer:
  __target__: vm
  save_dir: results_vm_max_multires_test_epoch99
  save_name: denoised
