mode: predict
debug: false

load_ckpt: experiments/straightpcf_max/checkpoint_best_cd0.0002_iter5000.pkl

components:
  data: predict_val
  transform: predict
  system: vm
  model: straightpcf_max

writer:
  __target__: vm
  save_dir: results_val_spcf_max
  save_name: denoised
