mode: predict
debug: false

load_ckpt: experiments/cvm_max/checkpoint_149.pkl

components:
  data: predict
  transform: predict
  system: vm
  model: cvm_max

writer:
  __target__: vm
  save_dir: results_cvm_max_test_epoch149_near150
  save_name: denoised
