mode: predict
debug: false

# Set after SPCF training (experiments/straightpcf_max/)
load_ckpt: experiments/straightpcf_max/checkpoint_best_cd0.0002_iter5000.pkl

components:
  data: predict
  transform: predict
  system: vm
  model: straightpcf_max

writer:
  __target__: vm
  save_dir: results_spcf_max_test
  save_name: denoised
