mode: predict
debug: false

load_ckpt: experiments/cvm_max_multires/checkpoint_best_cd0.0002_epoch121.pkl

components:
  data: predict_fast
  transform: predict
  system: vm
  model: cvm_max

writer:
  __target__: vm
  save_dir: results_cvm_max_multires_test_epoch121
  save_name: denoised
