mode: train
seed: 123

cvm_ckpt: experiments/cvm_max/checkpoint_best_cd0.0002_epoch97.pkl

components:
  data: train_spcf_max_cloud
  transform: straightpcf_official
  system: straightpcf_max_frozen
  model: straightpcf_max_frozen

loss:
  loss: 1.0

optimizer:
  __target__: adam
  lr: 0.0001
  weight_decay: 0

trainer:
  max_iters: 90000
  val_freq: 5000
  start_iter: 0
  log_interval: 100
  max_grad_norm: 1000000000
