mode: train
debug: False

load_ckpt: experiments/vm_max/checkpoint_best_cd0.0002_epoch121.pkl

components:
  data: train_vm_max_cloud
  transform: vm
  system: vm_max
  model: vm_max

loss:
  loss: 1.0

optimizer:
  __target__: adam
  lr: 0.00005

trainer:
  epochs: 200
  start_epoch: 122
  save_every: 20
  val_chamfer_every: 1
  val_chamfer_max_samples: 20
